#ifndef APPCONSTANT_H_INCLUDE
#define APPCONSTANT_H_INCLUDE

#define STUDENT_NAME_LEN 64 
#define REGISTRATION_NUMBER_LEN 32 
#define MAIL_LEN 32
#define PROGRAM_NAME_LEN 32
#define PROGRAM_STATUS_LEN 32



#endif //APPCONSTANT_H_INCLUDE
